### ISSUE TITLE
Can't start second round with this team setup

### ISSUE THREAD

**Issue by LopsanJesus** [franciscolopezsanchez/timesup#40]
const initialState = {
  players: [
    {name: "jesus", team: 0, team_name: "Equipo Azul"},
    {name: "rocio", team: 0, team_name: "Equipo Azul"},
    {name: "roko", team: 0, team_name: "Equipo Azul"},
    {name: "cris", team: 1, team_name: "Equipo Amarillo"},
    {name: "curro", team: 1, team_name: "Equipo Amarillo"},
  ],
}

**Comment by franciscolopezsanchez** [comment]
Not happening
